[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "sdk-stubs"
version = "0.1.0"

[tool.setuptools.packages.find]
where = ["stubs"]

[tool.setuptools.package-data]
"*" = ["*"]