from typing import Dict, Any

def parse(content: str) -> Dict[str, Any]: ...
def load(filename: str) -> Dict[str, Any]: ...
def serialize(data: Dict[str, Any]) -> str: ...
def save(filename: str, data: Dict[str, Any]) -> None: ...
